/**
 * CaptionFlow — Caption Style Presets
 * 10 professionally designed presets for modern short-form video.
 * All original designs inspired by common editing conventions.
 */

import type { CaptionStyle } from '../types';

export const CAPTION_PRESETS: CaptionStyle[] = [
  // ─── 1. Clean Bold ───────────────────────────────────────────────────────
  {
    preset_name: 'Clean Bold',
    font_family: 'Poppins',
    font_size: 42,
    font_weight: '800',
    text_color: '#FFFFFF',
    highlight_color: '#FFD700',
    background_enabled: false,
    background_color: '#000000',
    background_opacity: 0,
    background_padding: 0,
    border_radius: 0,
    outline_enabled: true,
    outline_color: '#000000',
    outline_thickness: 3,
    shadow_enabled: false,
    shadow_color: '#000000',
    shadow_intensity: 0,
    shadow_offset_x: 0,
    shadow_offset_y: 0,
    vertical_position: 0.85,
    horizontal_alignment: 'center',
    max_chars_per_line: 35,
    line_spacing: 1.3,
    letter_spacing: 0,
    animation: 'fade',
    word_highlight_enabled: false,
    word_highlight_color: '#FFD700',
  },

  // ─── 2. Modern White ─────────────────────────────────────────────────────
  {
    preset_name: 'Modern White',
    font_family: 'Inter',
    font_size: 36,
    font_weight: '600',
    text_color: '#FFFFFF',
    highlight_color: '#60A5FA',
    background_enabled: true,
    background_color: '#000000',
    background_opacity: 0.55,
    background_padding: 12,
    border_radius: 8,
    outline_enabled: false,
    outline_color: '#000000',
    outline_thickness: 0,
    shadow_enabled: false,
    shadow_color: '#000000',
    shadow_intensity: 0,
    shadow_offset_x: 0,
    shadow_offset_y: 0,
    vertical_position: 0.87,
    horizontal_alignment: 'center',
    max_chars_per_line: 40,
    line_spacing: 1.4,
    letter_spacing: 0,
    animation: 'fade',
    word_highlight_enabled: false,
    word_highlight_color: '#60A5FA',
  },

  // ─── 3. High Contrast ────────────────────────────────────────────────────
  {
    preset_name: 'High Contrast',
    font_family: 'Montserrat',
    font_size: 44,
    font_weight: '900',
    text_color: '#000000',
    highlight_color: '#FF0000',
    background_enabled: true,
    background_color: '#FFFFFF',
    background_opacity: 1.0,
    background_padding: 10,
    border_radius: 4,
    outline_enabled: false,
    outline_color: '#000000',
    outline_thickness: 0,
    shadow_enabled: false,
    shadow_color: '#000000',
    shadow_intensity: 0,
    shadow_offset_x: 0,
    shadow_offset_y: 0,
    vertical_position: 0.85,
    horizontal_alignment: 'center',
    max_chars_per_line: 32,
    line_spacing: 1.2,
    letter_spacing: -1,
    animation: 'pop',
    word_highlight_enabled: false,
    word_highlight_color: '#FF0000',
  },

  // ─── 4. Creator Pop ──────────────────────────────────────────────────────
  {
    preset_name: 'Creator Pop',
    font_family: 'Poppins',
    font_size: 48,
    font_weight: '900',
    text_color: '#FFFFFF',
    highlight_color: '#FF6B35',
    background_enabled: true,
    background_color: '#FF6B35',
    background_opacity: 1.0,
    background_padding: 10,
    border_radius: 12,
    outline_enabled: false,
    outline_color: '#000000',
    outline_thickness: 0,
    shadow_enabled: true,
    shadow_color: '#000000',
    shadow_intensity: 0.4,
    shadow_offset_x: 3,
    shadow_offset_y: 3,
    vertical_position: 0.83,
    horizontal_alignment: 'center',
    max_chars_per_line: 28,
    line_spacing: 1.2,
    letter_spacing: 0,
    animation: 'pop',
    word_highlight_enabled: false,
    word_highlight_color: '#FFD700',
  },

  // ─── 5. Minimal ──────────────────────────────────────────────────────────
  {
    preset_name: 'Minimal',
    font_family: 'Inter',
    font_size: 30,
    font_weight: '400',
    text_color: '#EEEEEE',
    highlight_color: '#FFFFFF',
    background_enabled: false,
    background_color: '#000000',
    background_opacity: 0,
    background_padding: 0,
    border_radius: 0,
    outline_enabled: true,
    outline_color: '#000000',
    outline_thickness: 1,
    shadow_enabled: true,
    shadow_color: '#000000',
    shadow_intensity: 0.6,
    shadow_offset_x: 1,
    shadow_offset_y: 2,
    vertical_position: 0.88,
    horizontal_alignment: 'center',
    max_chars_per_line: 45,
    line_spacing: 1.5,
    letter_spacing: 0,
    animation: 'fade',
    word_highlight_enabled: false,
    word_highlight_color: '#FFFFFF',
  },

  // ─── 6. Neon Highlight ───────────────────────────────────────────────────
  {
    preset_name: 'Neon Highlight',
    font_family: 'Montserrat',
    font_size: 40,
    font_weight: '800',
    text_color: '#FFFFFF',
    highlight_color: '#00FF88',
    background_enabled: false,
    background_color: '#000000',
    background_opacity: 0,
    background_padding: 0,
    border_radius: 0,
    outline_enabled: true,
    outline_color: '#00CC66',
    outline_thickness: 2,
    shadow_enabled: true,
    shadow_color: '#00FF88',
    shadow_intensity: 0.8,
    shadow_offset_x: 0,
    shadow_offset_y: 0,
    vertical_position: 0.85,
    horizontal_alignment: 'center',
    max_chars_per_line: 35,
    line_spacing: 1.3,
    letter_spacing: 1,
    animation: 'fade',
    word_highlight_enabled: true,
    word_highlight_color: '#00FF88',
  },

  // ─── 7. Podcast Style ────────────────────────────────────────────────────
  {
    preset_name: 'Podcast Style',
    font_family: 'Inter',
    font_size: 32,
    font_weight: '500',
    text_color: '#FFFFFF',
    highlight_color: '#60A5FA',
    background_enabled: true,
    background_color: '#1A1A2E',
    background_opacity: 0.9,
    background_padding: 16,
    border_radius: 12,
    outline_enabled: false,
    outline_color: '#000000',
    outline_thickness: 0,
    shadow_enabled: false,
    shadow_color: '#000000',
    shadow_intensity: 0,
    shadow_offset_x: 0,
    shadow_offset_y: 0,
    vertical_position: 0.82,
    horizontal_alignment: 'center',
    max_chars_per_line: 42,
    line_spacing: 1.6,
    letter_spacing: 0,
    animation: 'fade',
    word_highlight_enabled: false,
    word_highlight_color: '#60A5FA',
  },

  // ─── 8. Word Highlight ───────────────────────────────────────────────────
  {
    preset_name: 'Word Highlight',
    font_family: 'Poppins',
    font_size: 44,
    font_weight: '700',
    text_color: '#FFFFFF',
    highlight_color: '#FACC15',
    background_enabled: false,
    background_color: '#000000',
    background_opacity: 0,
    background_padding: 0,
    border_radius: 0,
    outline_enabled: true,
    outline_color: '#000000',
    outline_thickness: 3,
    shadow_enabled: false,
    shadow_color: '#000000',
    shadow_intensity: 0,
    shadow_offset_x: 0,
    shadow_offset_y: 0,
    vertical_position: 0.85,
    horizontal_alignment: 'center',
    max_chars_per_line: 32,
    line_spacing: 1.3,
    letter_spacing: 0,
    animation: 'word_highlight',
    word_highlight_enabled: true,
    word_highlight_color: '#FACC15',
  },

  // ─── 9. Cinematic ────────────────────────────────────────────────────────
  {
    preset_name: 'Cinematic',
    font_family: 'Montserrat',
    font_size: 34,
    font_weight: '600',
    text_color: '#F5F5DC',
    highlight_color: '#D4AF37',
    background_enabled: false,
    background_color: '#000000',
    background_opacity: 0,
    background_padding: 0,
    border_radius: 0,
    outline_enabled: false,
    outline_color: '#000000',
    outline_thickness: 0,
    shadow_enabled: true,
    shadow_color: '#000000',
    shadow_intensity: 0.8,
    shadow_offset_x: 2,
    shadow_offset_y: 3,
    vertical_position: 0.88,
    horizontal_alignment: 'center',
    max_chars_per_line: 40,
    line_spacing: 1.5,
    letter_spacing: 2,
    animation: 'fade',
    word_highlight_enabled: false,
    word_highlight_color: '#D4AF37',
  },

  // ─── 10. Viral Short-Form ─────────────────────────────────────────────────
  {
    preset_name: 'Viral Short-Form',
    font_family: 'Poppins',
    font_size: 52,
    font_weight: '900',
    text_color: '#FFFFFF',
    highlight_color: '#FF4757',
    background_enabled: false,
    background_color: '#000000',
    background_opacity: 0,
    background_padding: 0,
    border_radius: 0,
    outline_enabled: true,
    outline_color: '#000000',
    outline_thickness: 4,
    shadow_enabled: true,
    shadow_color: '#FF4757',
    shadow_intensity: 0.4,
    shadow_offset_x: 0,
    shadow_offset_y: 4,
    vertical_position: 0.82,
    horizontal_alignment: 'center',
    max_chars_per_line: 25,
    line_spacing: 1.2,
    letter_spacing: -1,
    animation: 'pop',
    word_highlight_enabled: false,
    word_highlight_color: '#FF4757',
  },
];

export const DEFAULT_STYLE: CaptionStyle = CAPTION_PRESETS[0];
